name: Create Preview Builds

on:
  push:
    branches:
      - main

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: preview
  # Disable iOS builds because I don't intend to 
  # build_ios:
  #   type: build
  #   params:
  #     platform: ios
  #     profile: preview
